application:
  async:
    executor:
      - name: integration-client
        core-pool-size: 2
        max-pool-size: 2
        queue-capacity: 10
      - name: broadcast
        core-pool-size: 5
        max-pool-size: 10
        queue-capacity: 100
      - name: scheduler
        core-pool-size: 2
  bot:
    admin:
      id: ${APP_ADMIN_ID:}
    token: ${APP_BOT_TOKEN:}
    username: ValentinGentlemanBot
  broadcast:
    blackout:
      start: '19:00'  # UTC
      end: '06:00'  # UTC
    interval: 25200  # Seconds
  integration:
    client:
      dropbox:
        name: compliment-bot-backup-client
        access-token: ${APP_DBX_ACCESS_TOKEN:}
      romantic-collection:
        url: https://love.romanticcollection.ru/blog/500-trogatelnyh-komplimentov-devushke/
        read-timeout: 5000
      infoniac:
        url: https://www.infoniac.ru/news/150-komplimentov-cheloveku-priyatnye-slova-kotorye-podnimut-nastroenie-lyubomu.html
        read-timeout: 5000
    dropbox:
      root-dir: ''
  storage:
    backup-time: '18:00'  # UTC
    cache-file-name: storage.json
    cache-location: /opt/tg-bots/compliment-bot/cache/${application.storage.cache-file-name}
