application:
  id: clxox1usm00005k91h5eqfelw
  async:
    executor:
      - name: integration-client
        core-pool-size: 2
        max-pool-size: 2
        queue-capacity: 10
      - name: broadcast
        core-pool-size: 5
        max-pool-size: 10
        queue-capacity: 100
      - name: scheduler
        core-pool-size: 2
  bot:
    admin:
      id: #
    token: #
    username: Валентин-джентльмен бот
  broadcast:
    blackout:
      start: '19:00'  # UTC
      end: '06:00'  # UTC
    interval: 25200  # Seconds. 7 hours by default
  integration:
    client:
      romantic-collection:
        url: https://love.romanticcollection.ru/blog/500-trogatelnyh-komplimentov-devushke/
        read-timeout: 5000
      infoniac:
        url: https://www.infoniac.ru/news/150-komplimentov-cheloveku-priyatnye-slova-kotorye-podnimut-nastroenie-lyubomu.html
        read-timeout: 5000
  storage:
    backup-time: '18:00'  # UTC
    location: /opt/tg-bots/${id}/storage.json
